spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        # AUTH SERVICE
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 20

        - id: auth-login
          uri: lb://auth-service
          predicates:
            - Path=/auth/login
            - Method=POST
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@loginKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1

        # PRODUCT SERVICE - PRODUCTS
        - id: product-service-products
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 20

        # PRODUCT SERVICE - CATEGORIES
        - id: product-service-categories
          uri: lb://product-service
          predicates:
            - Path=/categories/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 20

        # PRODUCT SERVICE - PACKS
        - id: product-service-packs
          uri: lb://product-service
          predicates:
            - Path=/packs/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 20

          # ORDER SERVICE
        - id: pedido-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 20

        # FEDEX
        - id: pedido-fedex
          uri: lb://order-service
          predicates:
            - Path=/orders/fedex/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1

        # CLIENTS
        - id: order-clients
          uri: lb://order-service
          predicates:
            - Path=/clients/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 20

        # ANALYTICS
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/analytics/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 20

        # REPORTE MENSUAL
        - id: analytics-monthly-report
          uri: lb://analytics-service
          predicates:
            - Path=/analytics/reports/generate/monthly
            - Method=POST
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1

        # REPORTE MENSUAL IA
        - id: analytics-ai-monthly-report
          uri: lb://analytics-service
          predicates:
            - Path=/analytics/reports/generate/ia/monthly
            - Method=POST
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1

        # REPORTE ANUAL IA
        - id: analytics-ai-annual-report
          uri: lb://analytics-service
          predicates:
            - Path=/analytics/reports/generate/ia/year
            - Method=GET
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1

server:
  port: 9093

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET}